### ISSUE TITLE
Github OAuth2 로그인

### ISSUE THREAD

**Issue by sangwoo-98** [SSTOF/SSTOF-Server#4]
프론트에서 `/oauth2/authorization/github`로 요청을 보내는데, 이게 회원가입 시랑 로그인 시에 같은 URL로 보내는 방법 밖에 없는 것 같아.
그럼 기존에 이 엔드포인트로 요청홨을 때 `GithubEmailInUseException` 던져서 `AuthenticationFailureHandler` 구현체에서 처리하도록 했는데, 이 단계를 없애야 할까?

간단히 말하면, 로그인인지 회원가입인지를 구분하는 방법을 모르겠다는 말!

**Comment by puroong** [comment]
다른 앱 보니까 로그인&회원가입 구분 안하고 `카카오로 로그인하기`하면 카카오 로그인 폼으로 회원 인증하고 바로 로그인 처리 해주는 것 같아
이게 사용자 입장에선 편할 것 같다는 생각이 드는데, 문제는 access token을 클라이언트에 어떻게 전달해야 할 지 고민되네..ㅠㅠ
oauth 인증 끝나면 주어진 redirect uri 리다이렉트 하니까 access token을 헤더에 넣거나, 쿼리 파라미터로 전달해야 할 것 같은데 보안에 문제가 없는지 검토해봐야 할 것 같아

**Comment by sangwoo-98** [comment]
헤더에 넣어도 되지 않나? 어짜피 response body로 보내서 localStorage든 sessionStorage든 저장하면 콘솔에서 볼 수 있는 거자나!

**Comment by puroong** [comment]
헤더가 좋을 거 같아!
