### ISSUE TITLE
일반 회원가입 회원과 OAuth 회원들의 구분

### ISSUE THREAD

**Issue by sangwoo-98** [SSTOF/SSTOF-Server#7]
회원 가입 처리를 할 때, 일반 회원 가입을 하면 비밀번호를 입력하고, 그 값을 인코딩해서 데이터베이스에 넣는데, OAuth로 가입한 회원들은 비밀번호가 null 이야.

만약 내가 OAuth로 `a@a.com`으로 가입하면, 그 행의 비밀번호는 null인데, 사용자가 로그인 폼을 채워서 `a@a.com`으로 로그인하면 비밀번호가 없다고 400(BAD_REQUEST) 응답이 오도록 되어 있어..

그래서 해결책을 생각해봤는데..

1. OAuth 회원용 테이블을 따로 만든다.
2. OAuth 가입인지, 일반 가입인지를 구별하는 컬럼을 하나 만든다.

뭐가 좋을까?

**Comment by puroong** [comment]
2번이 나을 거 같아
레진 코믹스에선 페이스북 oauth로 가입한 계정은 계속 페이스북으로만 로그인 할 수 있게 하는 거 같아!
![Uploading Screenshot from 2021-03-17 16-16-28.png…]()

**Comment by sangwoo-98** [comment]
음 okay 오늘 내로 변경해보껭
